version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'schulungsportal'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'my-secret-pw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql   

  web:    
    container_name: web
    build:
      dockerfile: ./Dockerfile
    image: schulungsportal
    depends_on: mysql  
    environment:
      DATABASE_HOST: database
      DATABASE_PASSWORD: Password      
    ports:
      - 5001:5001
      - 5000:5000


# Names our volume
volumes:
  my-db:
  webapp:


